name: Build and Deploy demo-order-data

on:
  push:
    branches: [  main ]
  pull_request:
    branches: [  main ]

env:
  APP_NAME: cloud-infra
  NAMESPACE: sample
  CLUSTER_NAME: dashboards-dev
  CLUSTER_PROJECT: zs-devops
  GCR_PROJECT: zs-devops
  STAGE_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  GCR_KEY: ${{ secrets.GCR_KEY }}

jobs:
  build:
    name: 🧪 Unit Tests and 🔨 Build
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push')

    steps:
      - name: trigger the automated test
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_PAT }}
          repository: zopsmart/test-paper-automation/.github/workflows/compiler_trigger.yml@main
          event-type: compiler_testing