name: Build and Deploy demo-order-data

on:
  push:
    branches: [  main ]
  pull_request:
    branches: [  main ]

jobs:
  build:
    name: 🧪 Unit Tests and 🔨 Build
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push')

    steps:
      - name: trigger the automated test
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ./.github/workflows/test.yml@main
          event-type: compiler_testing