name: Go - Lint, Test & Build

on:
  pull_request:
    types: [review_requested]
    branches:
      - main
  push:
    tags:
      - '*'
    branches:
      - main

jobs:


  stage_deployment:
    if: (github.ref == 'refs/heads/main') && (github.event_name == 'push')
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_commands: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main
            artifact_path: main
            DOCKER_FILE_PATH: "." # add step to grant executable permission to binary in docker file ex. chmod 777 /main
            app_name: samp1
            namespace: test
    uses: priyasingh-zs/inventory-func/.github/workflows/go_gar_stage_deploy.yaml@main
    with:
      BUILD_COMMAND: ${{ matrix.build_commands }}
      ARTIFACT_PATH: ${{ matrix.artifact_path }}
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: modified-fabric-408810
      GAR_REGISTRY: samp1
      CLUSTER_PROJECT: modified-fabric-408810
      CLUSTER_NAME: test-dev
      HELM_VALUES_PATH: ./helm-values/stage.yaml
      SHA: ${{ needs.test.outputs.SHA }}
    secrets:
      PAT: ${{ secrets.PAT }}
      GAR_KEY: ${{ secrets.GAR_KEY }}