name: Build and Deploy demo-order-data

on:
  push:
    branches: [  main ]
  pull_request:
    branches: [  main ]

env:
  APP_NAME: cloud-infra
  NAMESPACE: sample
  CLUSTER_NAME: dashboards-dev
  CLUSTER_PROJECT: zs-devops
  GCR_PROJECT: zs-devops
  STAGE_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  GCR_KEY: {"auths":{"us-central1-docker.pkg.dev":{"email":"image-pull@gcr","password":"{\n  \"type\": \"service_account\",\n  \"project_id\": \"zs-devops\",\n  \"private_key_id\": \"3348c1cdd66d421c14b2db877841429b39be7ad6\",\n  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClIxYRrywAJFiU\\n9mu28L2U3CXLiMce73sXaJlwJC4DkaCpuc8S9ZDt33Fcc+sRMIitTY9gQV/TuS+v\\nDKrTyq2VnLPATZEgIq07A8e8AyKNKwgdPgTBVqeb+qFxQ6iHXL3MRDxr15z1JYwW\\nTadmhcdwpENRcEleXYcX3lNgl2CSJptWk0fiVAga5U+ADzQx9b9nHS0IB6Ki055r\\nt7ds/vhFfSEio9U9nt6oFKD6U8JTE7UpUxrSOB8wSOFrEmeg63U0bVnMOKYbu1nu\\n0YpN2iubXyes72rXmBEGRPqs+qwEvPxNpsYjf9kEo5vcjPw0MrcT0bUGpGbT5yLN\\nO5IhYlafAgMBAAECggEAJ0kUi/p3ZkU/SZjiATB+eXZyC1yrukFQsD3zGsmQpMq1\\nRQtuJt2CsARTLKJrDrjUGx5zeHu092J75JIH5cC20Pvpi1soplN5kKuSjbjVNG5D\\nTOmfKfuafjH+zDpDUoiOopStJx6xOWTIUdoBdBNpYfPCDBLBcZCgfd4nSbhZggsI\\n2JdILvVTcW5VU+hpbiu4H+mXwx3/3YOgleh2OVNMP1Zfeq22Wx6fO2oo1/soHkj7\\njx20vACQyh7X+r3gn6/3orUe5/6NY43dPfu4MrFwcq4EhwjtX1LWCbuUoBgQyqZk\\nP2W2wJQFwXYMFCUlZ38E0oYJdlQqdARM/iuSoq+SEQKBgQDkET3R1SEoDWzGvYto\\nXnkWC2DVMq0WzjA0twq3jgbJy+y+ipluEVRNHdokFxBa1b6dGgRm/C4DiYz5twk4\\nZ2tD1VPSIh6butK61cYry+AIcTS2rp/wSizbtUZkWHjh1A2yr2RCJWbAt0zUBk4O\\nYUyHVAZFbb+1EkTUUHMA+iVIRwKBgQC5XL8LMCGtWjybLcXUrua+nIyM9LxXqB3J\\nmsf1YdvluZtwSYB+PtiPgNir2IqMn65J2/Vl5XxLUqvHfpvB5I1B9fOn7WYOvpQ+\\na8SD2xfKAO2einY4+/xegQ+w0gp4Mdj2aA8WJ/0LZ5jtRU4f6O1wVePFK723rk/h\\nH9J0coUC6QKBgC+6V/iYpKawIIp60jjWRHrTiME1KLn0DmyJvclqBIuojHPXp4I8\\nSCsXSzZwSTDpOEnCTxeKQMrmt0TvBBP0uKLqeu8nysYGU+FbqWwy70B1CHYOl1P/\\nAeI8zm1jgnCoIvG4+L9K+nTsJzzb0Ov7ert7XxCahhsLprHT4C1dK/4zAoGBAID5\\nJ3SBaO1VfBX9I0l46NR32NO69dGICDHeoIL8NCUDoEPg4Kb203gGDryDTuPJt1ts\\n0LK1mmZOf3evgHDItgDPQVn2tKxNrphAI9wa9dJ4Et3dOaUsr8yRwHknrGE1TeEl\\nRloEOO1Wh/GP52wMhilDmdf3N2o2vx3FJoofpK0BAoGBAL2cNBtkypCDLo8hjuIN\\nUCUAtdj5CZVkD93NIdgVBIq0MrBmiwaALkiD0ZBkSRSa4UxJPzbrZ0OJAAOM0tNK\\nshmoIHPVHLROT0ObRUA5/W3LPWfLzDMkfUu3F6oZiJ14BEhxQav3mXinUB2KXaKY\\n0TmBNb0hSE3S5/DU9CIep6Yo\\n-----END PRIVATE KEY-----\\n\",\n  \"client_email\": \"z3768-40100-cloud-infra@zs-devops.iam.gserviceaccount.com\",\n  \"client_id\": \"107572096474046589005\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/z3768-40100-cloud-infra%40zs-devops.iam.gserviceaccount.com\",\n  \"universe_domain\": \"googleapis.com\"\n}\n","username":"_json_key"}}}
jobs:
  build:
    name: 🧪 Unit Tests and 🔨 Build
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push')

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          id: Go

      - name: Checkout code into go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          git config --global url."https://${{ secrets.STAGE_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global http.sslVerify false
          go mod download

      - name: Make Directory
        run: mkdir build

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ env.GCR_KEY }}

      - name: Build and Push Docker Image to GCR
        run: |
          docker build -t inv:67 .
          docker tag inv:67 gcr.io/${{ env.GCR_PROJECT }}/${{ env.APP_NAME }}:${{ github.sha }}
          docker push gcr.io/${{ env.GCR_PROJECT }}/${{ env.APP_NAME }}:${{ github.sha }}


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.CLUSTER_PROJECT }}
          service_account_key: ${{ env.STAGE_DEPLOY_KEY }}
          export_default_credentials: true

      - name: Set GCloud Project and Fetch Cluster Credentials
        run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }}  --region=us-central1 --project=${{ env.CLUSTER_PROJECT }}

      - name: Update Deployment Image
        run: kubectl set image deployment/${{ env.APP_NAME }} ${{ env.APP_NAME }}=gcr.io/${{ env.GCR_PROJECT }}/${{ env.APP_NAME }}:${{ github.sha }} --namespace ${{ env.NAMESPACE }}

