name: Go - Lint, Test & Build

on:
  pull_request:
    types: [review_requested]
    branches:
      - main
      - master
      - development
  push:
    tags:
      - '*'
    branches:
      - main
      - master
      - development

jobs:
  test:
    uses: priyasingh-zs/inventory-func/.github/workflows/go_build.yaml@main
    with:
      POSTMAN_ENABLED: false
      TESTCOVERAGE_THRESHOLD: 10
      APP_NAME: order-data
    secrets:
      PAT: ${{ secrets.PAT }}

  build_dockerize:
    needs: [ test ]
    name: Build & dockerize
    uses: priyasingh-zs/inventory-func/.github/workflows/build_and_dockerize.yaml@main
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_commands: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main
            artifact_path: main
            DOCKER_FILE_PATH: "."
            app_name: order-data
    with:
      BUILD_COMMAND: ${{ matrix.build_commands }}
      ARTIFACT_PATH: ${{ matrix.artifact_path }}
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      APP_NAME: ${{ matrix.app_name }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: zs-devops
      GAR_REGISTRY: order-data
      SHA: ${{ needs.test.outputs.SHA }}
    secrets:
      PAT: ${{ secrets.PAT }}
      GAR_KEY: ${{ secrets.DEPLOY_KEY }}

  stage_deployment:
    needs: [ build_dockerize ]
    name: Stage deploy
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: order-data
            namespace: samp
    uses: priyasingh-zs/inventory-func/.github/workflows/go_gar_stage_deploy.yaml@main
    with:
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      CLUSTER_PROJECT: modified-fabric-408810
      CLUSTER_NAME: testing-dev
      HELM_VALUES_PATH: ./helm-values/stage.yaml
      IMAGE: ${{ needs.build_dockerize.outputs.IMAGE }}
      ENV_FILE_PATH: ./configs/.stage.env
    secrets:
      PAT: ${{ secrets.PAT }}
      GAR_KEY: ${{ secrets.DEPLOY_KEY }}


  prod_deployment:
    name: Prod deploy
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: order-data
            namespace: sample
    uses: priyasingh-zs/inventory-func/.github/workflows/go_gar_prod_deploy.yaml@main
    with:
      APP_NAME: ${{ matrix.app_name }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: zs-devops
      GAR_REGISTRY: order-data
      CLUSTER_PROJECT: zs-devops
      CLUSTER_NAME: test-dev
      NAMESPACE: ${{ matrix.namespace }}
      HELM_VALUES_PATH: ./helm-values/prod.yaml
    secrets:
      PAT: ${{ secrets.PAT }}
      GAR_KEY: ${{ secrets.DEPLOY_KEY }}