
name: TestPaper Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  app_name: TestPaper-test-automation
  RESULTS_DIRECTORY: ./src/main/resources/Workflow/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: compiler/build/reports/tests/test

  test_compiler_engine:
    name: Automation tests for compiler engine
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Compiler Engine Tests
        run: |
          cd compiler
          ./gradlew clean build -Dsuite=CompilerAutomation.xml -i

      - name:  Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: compiler/build/reports/tests/test